### ISSUE TITLE
Error installing in Unity 2023.1 beta / 2023.2 alpha

### ISSUE THREAD

**Issue by gradeeterna** [needle-tools/animation-utils#1]
Hey! Love these utilities, thanks for sharing them!

It works great in 2022.3 LTS, but I'm getting the following error when trying to install in 2023.1 beta / 2023.2 alpha - 

```
Library\PackageCache\com.needle.animation-utils@0.3.0-exp\Editor\MissingClipBindings\Internals\AnimationWindowHierarchyNodeAccess.cs(104,34): error CS7036: 

There is no argument given that corresponds to the required formal parameter 'node' of 'AnimationWindowUtility.IsNodeLeftOverCurve(AnimationWindowState, AnimationWindowHierarchyNode)'
```

Any ideas on how to fix would be much appreciated!

**Comment by marwie** [comment]
Looks like Unity changed the method in 2023 then. We can fix it when it's out of beta/alpha.

https://github.com/Unity-Technologies/UnityCsReference/blob/18e481fd5dbda630b82f4f4c59a2a0164ed75ebd/Editor/Mono/Animation/AnimationWindow/AnimationWindowUtility.cs#L141

Can be fixed by a compiler #ifdef for 2023 and passing in the required args here:
https://github.com/needle-tools/animation-utils/blob/911a58e5ec7df444bc53a960e00be135863cb4d2/package/Editor/MissingClipBindings/Internals/AnimationWindowHierarchyNodeAccess.cs#L104

**Comment by marwie** [comment]
If you can add a PR for 2023 that would be great

**Comment by marwie** [comment]
fixed by https://github.com/needle-tools/animation-utils/pull/2
